repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(notebooks/|examples/|docs/)
      - id: end-of-file-fixer
        exclude: ^(notebooks/|examples/|docs/)
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^(notebooks/|examples/|docs/)
      - id: ruff-format
        exclude: ^(notebooks/|examples/|docs/)
